import "../globals.css";

import dbConnect from "@/config/mongo.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();
  return (
    <html lang="en" className="scroll-smooth">
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
