import "../globals.css";
import Nav from "@/components/nav.jsx";
import Footer from "@/components/footer.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={` antialiased`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
